const PRODUCTION_ORIGIN="https://mahin98250.github.io/Dudh-Wallah";
let mode="signin";
const form=document.getElementById("authForm"),fullName=document.getElementById("fullName"),email=document.getElementById("email"),password=document.getElementById("password"),submit=document.getElementById("submitAuth"),message=document.getElementById("authMessage"),googleAuth=document.getElementById("googleAuth"),forgotAuth=document.getElementById("forgotAuth"),phoneToggle=document.getElementById("phoneToggle"),phoneForm=document.getElementById("phoneForm"),phoneNumber=document.getElementById("phoneNumber"),sendOtp=document.getElementById("sendOtp"),verifyOtp=document.getElementById("verifyOtp"),otpCode=document.getElementById("otpCode");
function showMessage(text,error=false){message.textContent=text;message.className="auth-message show"+(error?" error":"")}
function getReturnPath(){const value=new URLSearchParams(location.search).get("return")||"/Dudh-Wallah/";return value.startsWith("/Dudh-Wallah/")?value:"/Dudh-Wallah/"}
function productionUrl(path){return PRODUCTION_ORIGIN+path}
function isLocalOrigin(){return /^(localhost|127\\.0\\.0\\.1|0\\.0\\.0\\.0)$/.test(location.hostname)||location.hostname.endsWith(".local")}
function productionGoogleUrl(){return productionUrl("/auth.html?oauth=google&return="+encodeURIComponent(getReturnPath()))}
function setMode(next){mode=next;document.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));document.getElementById("nameField").style.display=mode==="signup"?"grid":"none";submit.textContent=mode==="signup"?"Create account →":"Sign in →";document.getElementById("authTitle").textContent=mode==="signup"?"Join Doodhwala.":"Welcome back.";document.getElementById("authIntro").textContent=mode==="signup"?"Create your customer account to order local milk and save delivery addresses.":"Sign in to save addresses, place orders and manage your milk deliveries.";forgotAuth.style.display=mode==="signin"?"block":"none"}
function authError(err){const m=String(err?.message||err||"Authentication failed");if(/email.*rate limit|rate limit.*email|email rate.?limit|too many requests/i.test(m))return"Email sending is temporarily rate-limited by Supabase. Stop retrying for now and try again after the limit resets.";if(/password.*weak|password.*breached|compromised/i.test(m))return"Choose a stronger password that has not appeared in known data breaches.";if(/email.*not.*confirm|confirm.*email/i.test(m))return"Your account was created, but your email still needs verification. Check your inbox, then sign in.";if(/invalid login credentials/i.test(m))return"Email or password is incorrect.";if(/already registered|already been registered/i.test(m))return"An account already exists with this email. Try Sign in or reset the password.";if(/redirect.*url|not allowed/i.test(m))return"Authentication is configured, but this site's redirect URL is not allowed in Supabase.";return m}
function normalizePhone(v){const digits=v.replace(/\D/g,"");if(digits.length===10)return "+91"+digits;if(digits.length===12&&digits.startsWith("91"))return "+"+digits;return v.trim()}
async function ensureReady(){if(!window.Doodhwala?.configured){showMessage("Supabase is not configured.",true);return false}return true}
document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
setMode("signin");
form.onsubmit=async function(e){e.preventDefault();if(!await ensureReady())return;submit.disabled=true;try{if(mode==="signup"){const name=fullName.value.trim();if(name.length<2)throw new Error("Enter your full name.");const {data,error}=await Doodhwala.supabase.auth.signUp({email:email.value.trim(),password:password.value,options:{data:{full_name:name},emailRedirectTo:productionUrl("/auth.html?return="+encodeURIComponent(getReturnPath()))}});if(error)throw error;if(data.session){showMessage("Account created. Redirecting…");location.href=getReturnPath()}else showMessage("Account created. Check your email to verify it. After verification, return here and sign in.");}else{const {error}=await Doodhwala.supabase.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(error)throw error;showMessage("Signed in. Redirecting…");location.href=getReturnPath()}}catch(err){showMessage(authError(err),true)}finally{submit.disabled=false}};
googleAuth.onclick=async()=>{if(isLocalOrigin()){showMessage("Google sign-in uses the secure production site. Opening Doodhwala…");location.href=productionGoogleUrl();return}if(!await ensureReady())return;googleAuth.disabled=true;try{const {error}=await Doodhwala.supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:productionUrl("/auth.html?return="+encodeURIComponent(getReturnPath()))}});if(error)throw error}catch(err){showMessage(authError(err),true);googleAuth.disabled=false}};
const autoGoogle=new URLSearchParams(location.search).get("oauth")==="google";
if(autoGoogle&&!isLocalOrigin())setTimeout(()=>googleAuth.click(),80);
forgotAuth.onclick=async()=>{if(!await ensureReady())return;const e=email.value.trim();if(!e){showMessage("Enter your email first, then tap Forgot password.",true);return}try{const {error}=await Doodhwala.supabase.auth.resetPasswordForEmail(e,{redirectTo:productionUrl("/auth.html?reset=1&return="+encodeURIComponent(getReturnPath()))});if(error)throw error;showMessage("Password reset email sent. Check your inbox.")}catch(err){showMessage(authError(err),true)}};
phoneToggle.onclick=()=>{phoneForm.classList.toggle("hidden");phoneToggle.textContent=phoneForm.classList.contains("hidden")?"Use phone + OTP":"Hide phone + OTP"};
phoneForm.onsubmit=async e=>{e.preventDefault();if(!await ensureReady())return;sendOtp.disabled=true;try{const {error}=await Doodhwala.supabase.auth.signInWithOtp({phone:normalizePhone(phoneNumber.value)});if(error)throw error;showMessage("OTP requested. This requires phone authentication/SMS to be enabled in Supabase.");document.getElementById("otpField").classList.remove("hidden");verifyOtp.classList.remove("hidden")}catch(err){showMessage("Phone OTP is not enabled yet. Configure a phone/SMS provider in Supabase Auth first.",true)}finally{sendOtp.disabled=false}};
verifyOtp.onclick=async()=>{try{const {data,error}=await Doodhwala.supabase.auth.verifyOtp({phone:normalizePhone(phoneNumber.value),token:otpCode.value.trim(),type:"sms"});if(error)throw error;if(data.session)location.href=getReturnPath()}catch(err){showMessage(authError(err),true)}};